name: smartambulance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.2.0
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  geolocator: ^7.7.0
  geocoding: ^2.0.1
  pinput: ^5.0.0
  slide_to_act: ^2.0.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding/
    - assets/home/
    - assets/payment/
